server.port: 8080


database1.global.url: jdbc:postgresql://localhost:5432/db1
database1.global.username: user1
database1.global.password: pass1

database1.global:
  # увеличиваем количество одновременно возможных подключений к бд
  hikari.maximum-pool-size: 80
  hikari.poolName: global
  # считаем коннекты, не возвращавшиеся в пул в течении x мс утекшими
  hikari.leak-detection-threshold: 10000
  hikari.registerMbeans: true
  # https://github.com/brettwooldridge/HikariCP
  # An in-use connection will never be retired, only when it is closed will it then be removed.
  # Ограничение времени для всех запросов (в секундах)
  jdbc.template.query-timeout: 60


database2.global.url: jdbc:postgresql://localhost:5333/db2
database2.global.username: user2
database2.global.password: pass2

database2.global:
  # увеличиваем количество одновременно возможных подключений к бд
  hikari.maximum-pool-size: 80
  hikari.poolName: global
  # считаем коннекты, не возвращавшиеся в пул в течении x мс утекшими
  hikari.leak-detection-threshold: 10000
  hikari.registerMbeans: true
  # https://github.com/brettwooldridge/HikariCP
  # An in-use connection will never be retired, only when it is closed will it then be removed.
  # Ограничение времени для всех запросов (в секундах)
  jdbc.template.query-timeout: 60


spring.data.mongodb.host: 127.0.0.1
spring.data.mongodb.port: 27017
spring.data.mongodb.authentication-database: admin
spring.data.mongodb.username: user1
spring.data.mongodb.password: pass1
spring.data.mongodb.database: admin
spring:
  main:
    allow-bean-definition-overriding: true

management:
  #данная пропертя вкл/выкл проверку доступности БД при запросе actuator/health(по умолчанию вкл). Как выяснилось при частой такой проверки используется много памяти,
  #поэтому если вас такое поведение не устраивает можно это отключить. Подробности: https://jira.pcbltools.ru/jira/browse/EDU-27998
  health.db.enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      group:
        readiness:
          include: readinessState,db,mongo
        liveness:
          include: livenessState
    shutdown:
      enabled: true
    metric:
      enabled: true
    startup:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: prometheus, health ,shutdown, startup
  health.mail.enabled: false