version: "3"

services:

  mongo:
    image: mongo:3.4
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: pass1
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"

  db:
    image: postgres
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: db1
    restart: unless-stopped
    volumes:
      - ./postgres-data1:/var/lib/postgresql/data1
    ports:
      - "5432:5432"

  db2:
    image: postgres
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: db2
    restart: unless-stopped
    volumes:
      - ./postgres-data2:/var/lib/postgresql/data2
    ports:
      - "5333:5432"